version: '3.7'

services:
  blogapi_db:
    image: postgres:latest
    container_name: blogapi_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: blogapi_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - blogapi_db_data:/var/lib/postgresql/data


volumes:
  blogapi_db_data: